package Agents;

import java.util.Random;

import Model.AgentDataAccessInterface;
import Util.Constants;

import sim.engine.SimState;
import sim.engine.Steppable;



public class People implements Steppable
{

	/**
	 * Auto generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;
	
	
	// Abilities
	private int visionAbility;
	private int hearingAbility;
	private int panicLevel;
	private int charismaLevel;
	private int autonomyLevel;
	
	
	
	/**
	 * Default constructor
	 */
	public People()
	{
		// Generates abilities' rate
		visionAbility = getRandomAbility();
		hearingAbility = getRandomAbility();
		panicLevel = getRandomAbility();
		charismaLevel = getRandomAbility();
		autonomyLevel = getRandomAbility();
	}
	
	
	
	/**
	 * It generates a random ability's rate, which can take value from 1 to 10 (both included)
	 * 
	 * @return A random rate
	 */
	private int getRandomAbility()
	{
		Random generator = new Random();
		return (generator.nextInt(Constants.MAX_ABILITY) + 1);
	}
	
	

	@Override
	public void step(SimState arg0)
	{
		if(arg0 instanceof AgentDataAccessInterface)
		{
			AgentDataAccessInterface model = (AgentDataAccessInterface) arg0;
			
			updateStatus(model);
		}
	}
	
	
	
	/**
	 * It updates the agent's status, considering its environment
	 * 
	 * @param model The model to which the agent can ask informations
	 */
	private void updateStatus(AgentDataAccessInterface model)
	{
		if(model.canSeeFire(this))
		{
			
		}
	}

}
